Update the compare_to_wl script to use inclusive language
Renames to compare_to_symbol_list and updates instances of "whitelist"
to "symbollist".

Signed-off-by: Will McVicker <willmcvicker@google.com>
Bug: 161912438
Change-Id: I70753acfdc41d297436c8e6362eb75b659af0a0d

diff --git a/abi/compare_to_symbol_list b/abi/compare_to_symbol_list
--- a/abi/compare_to_symbol_list
+++ b/abi/compare_to_symbol_list
@@ -16,12 +16,12 @@
 
 if [ "$#" -ne 2 ]; then
 	echo "ERROR: illegal number of parameters" >&2
-	echo "Usage: compare_to_wl <path/to/Module.symvers> <path/to/whitelist>" >&2
+	echo "Usage: compare_to_wl <path/to/Module.symvers> <path/to/symbol-list>" >&2
 	exit 1
 fi
 
 ksymtab=$(mktemp)
-whitelist=$(mktemp)
+symbollist=$(mktemp)
 
 # List of objects, typically vmlinux + GKI modules
 objects="${KMI_STRICT_MODE_OBJECTS:-vmlinux}"
@@ -38,15 +38,15 @@ cut -d$'\t' -f2- $1 | while read line; do
 	echo "${ksym[0]}"
 done | sort -u > $ksymtab
 
-sort -u "$2" > $whitelist
+sort -u "$2" > $symbollist
 
-delta=$(diff -u $ksymtab $whitelist | grep -v ' ')
-rm $ksymtab $whitelist
+delta=$(diff -u $ksymtab $symbollist | grep -v ' ')
+rm $ksymtab $symbollist
 if [ -n "$delta" ]; then
-	echo "ERROR: Differences between ksymtab and whitelist detected!" >&2
+	echo "ERROR: Differences between ksymtab and symbol list detected!" >&2
 	echo "Symbols missing from ksymtab:" >&2
 	echo "$delta" | sed -n -e 's/^+/ - /p' >&2
-	echo "Symbols missing from whitelist:" >&2
+	echo "Symbols missing from symbol list:" >&2
 	echo "$delta" | sed -n -e 's/^-/ - /p' >&2
 	exit 1
 fi
